server:
  port: 8888

spring:
  application:
    name: victor-config-server
  profiles:
    active:
    - dev,perf,prod,qa
  cloud:
    config:
      server:
        git:
          uri: https://github.com/victorlobato2000/victor-microservices
          default-label: master
          search-paths:
            - 'victor-config-server\src\main\resources*'