server:
  port: 8888

spring:
  application:
    name: victor-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/victorlobato2000/victorlobato-config-server
          default-label: master
          search-paths:
            - 'greeting-service*'